services:
  postgres:
    image: postgres:15-alpine
    container_name: stalo-postgres-prod
    environment:
      POSTGRES_DB: stalo_db
      POSTGRES_USER: stalo_user
      POSTGRES_PASSWORD: stalo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
      - postgres
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    container_name: stalo-minio
    ports:
      - "9000:9000"      # API
      - "9001:9001"      # Console Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://stalo_user:stalo_password@postgres:5432/stalo_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=stalo_user
      - DB_PASSWORD=stalo_password
      - DB_DATABASE=stalo_db
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin123
      - MINIO_BUCKET=stalo-documents
    depends_on:
      - postgres
      - minio
    networks:
      - app-network

volumes:
  postgres_data:
  minio_data:

networks:
  app-network:
    driver: bridge
