services:
  postgres:
    image: postgres:15-alpine
    container_name: stalo-postgres
    environment:
      POSTGRES_DB: stalo_db
      POSTGRES_USER: stalo_user
      POSTGRES_PASSWORD: stalo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
      - postgres
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://stalo_user:stalo_password@postgres:5432/stalo_db
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=stalo_user
      - DB_PASSWORD=stalo_password
      - DB_DATABASE=stalo_db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
